require "exception_notification/rails"

app_name = Rails.application.credentials[:EXCEPTION_NAME]
recipient = Rails.application.credentials[:EXCEPTION_RECIPIENT]
webhook_url = Rails.application.credentials[:SLACK_WEBHOOK]
channel = Rails.application.credentials[:SLACK_CHANNEL]

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound,
  # AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  # config.ignored_exceptions += %w{ActionView::TemplateError CustomError}

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  config.ignore_if do |_exception, _options|
    !(Rails.env.production? || Rails.env.staging?)
  end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

  config.error_grouping = true
  config.error_grouping_period = 5.minutes

  # Notifiers =================================================================
  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: "[#{app_name}]",
    sender_address: %("Notifier" <notifier@mg.amastek.com>),
    exception_recipients: [recipient],
  }

  config.add_notifier :slack, {
    webhook_url:,
    channel:,
    username: app_name,
    additional_parameters: {
      icon_emoji: ":book:",
      mrkdwn: true,
    },
  }
end
