# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials[:DB_HOST] %>
  username: <%= Rails.application.credentials[:DB_USER] %>
  password: <%= Rails.application.credentials[:DB_PASSWORD] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: project_dev

test:
  <<: *default
  database: project_test

staging:
  <<: *default
  database: <%= Rails.application.credentials[:DB_NAME] %>
  
production:
  <<: *default
  database: <%= Rails.application.credentials[:DB_NAME] %>