name: Check Coding Style (FrontEnd)
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.vue'
      - '.nvmrc'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}-${{ steps.setup-node.outputs.node-version }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Install dependencies
        run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      
      - name: Lint check code
        run: yarn run eslint --ext .js --ext .jsx --ext .vue app/packs/src app/packs/entrypoints --format codeframe
